sudo: required
language: java
dist: trusty
services:
  - docker
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - oraclejdk8
  - oraclejdk9
before_install:
  - export TZ=Asia/Shanghai
script:
  - docker-compose up -d
  - mvn clean package -Dmaven.test.skip=true -q
  - java -cp target/clickhouse-native-jdbc-2.2-stable-SNAPSHOT-shaded.jar examples.TestFetchData "native" "1000000" "1"
  - java -cp target/clickhouse-native-jdbc-2.2-stable-SNAPSHOT-shaded.jar examples.TestFetchData "http" "1000000" "1"
  - java -cp target/clickhouse-native-jdbc-2.2-stable-SNAPSHOT-shaded.jar examples.TestFetchData "native" "1000000" "0"
  - java -cp target/clickhouse-native-jdbc-2.2-stable-SNAPSHOT-shaded.jar examples.TestFetchData "http" "1000000" "0"


