name: gh-pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: '[[ -z $(git show HEAD -- docs) ]] || npm install'
      - run: '[[ -z $(git show HEAD -- docs) ]] || npm run docs:build'
      - run: '[[ -z $(git show HEAD -- docs) ]] || dev/deploy_gh_pages.sh'
        env:
          PAGES_DEPLOY_TOKEN: ${{ secrets.PAGES_DEPLOY_TOKEN }}
